In [1]:
from __future__ import print_function
from numpy import array
from bezier import *
from fitCurves import *
from tkinter import *


# center of bounding box
def cntr(x1, y1, x2, y2):
    return x1+(x2-x1)/2, y1+(y2-y1)/2


# tkinter Canvas plus some addons
class MyCanvas(Canvas):
    def create_polyline(self, points, **kwargs):
        for p1, p2 in zip(points, points[1:]):
            self.create_line(p1, p2, kwargs)
            #print('p1:',p1,'p2:',p2)
            

    def create_bezier(self, b, tag):
        self.create_polyline([bezier.q(b, t/50.0).tolist() for t in range(0, 51)], tag=tag, fill='red', width='1') # there are better ways to draw a bezier
        #self.create_line(b[0].tolist(), b[1].tolist(), tag=tag)
        #self.create_point(b[1][0], b[1][1], 2, fill='black', tag=tag)
        #self.create_line(b[3].tolist(), b[2].tolist(), tag=tag)
        #self.create_point(b[2][0], b[2][1], 2, fill='black', tag=tag)
        #self.create_point(b[0][0],b[0][1],b[0][2],b[0][3],2, fill='black', tag=tag)

    def create_point(self, x, y, r, **kwargs):
        return self.create_oval(x-r, y-r, x+r, y+r, kwargs)


    def pos(self, idOrTag):
        return cntr(*self.coords(idOrTag))


    def itemsAtPos(self, x, y, tag):
        return [item for item in self.find_overlapping(x, y, x, y) if tag in self.gettags(item)]


class MainObject:
    def run(self):
        root = Tk()

        self.canvas = MyCanvas(root, bg='white', width=400, height=400)
        self.canvas.pack(side=LEFT)

        frame = Frame(root, relief=SUNKEN, borderwidth=1)
        frame.pack(side=LEFT, fill=Y)
        label = Label(frame, text='Max Error')
        label.pack()
        self.spinbox = Spinbox(frame, width=8, from_=0.0, to=1000000.0, command=self.onSpinBoxValueChange)
        self.spinbox.insert(0, 10.0)
        self.spinbox.pack()

        self.points = []
        self.draggingPoint = None

        self.canvas.bind('<ButtonPress-1>', self.onButton1Press)
        self.canvas.bind('<ButtonPress-2>', self.onButton2Press)
        self.canvas.bind('<B1-Motion>', self.onMouseMove)
        self.canvas.bind('<ButtonRelease-1>', self.onButton1Release)

        root.mainloop()


    def onButton1Press(self, event):
        items = self.canvas.itemsAtPos(event.x, event.y, 'point')
        #print(items)
        if items:
            self.draggingPoint = items[0]
            print('if')
        else:
            self.points.append(self.canvas.create_point(event.x, event.y, 4, fill='red', tag='point'))
            self.redraw()
            #print(event)
            #print(self.points)

    def onButton2Press(self, event):
        self.canvas.delete(self.points.pop())
        self.redraw()


    def onMouseMove(self, event):
        if self.draggingPoint:
            self.canvas.coords(self.draggingPoint, event.x-4, event.y-4, event.x+4, event.y+4)
            self.redraw()


    def onButton1Release(self, event):
        self.draggingPoint = None


    def onSpinBoxValueChange(self):
        self.redraw()


    def redraw(self):
        # redraw polyline
        self.canvas.delete('polyline')
        self.canvas.create_polyline([self.canvas.pos(pId) for pId in self.points], fill='grey', tag='polyline')
        self.canvas.tag_lower('polyline')

        # redraw bezier
        if len(self.points) < 2:
            return

        self.canvas.delete('bezier')
        points = array([self.canvas.pos(p) for p in self.points])
        beziers = fitCurve(points, float(self.spinbox.get())**2)
        print('points:',points)
        print('type(points[0]):',type(points[0]))
       
        print('beziers:',beziers)
        print('type(beziers):',type(beziers))
        print('beziers[0]:',beziers[0])
        print('type(beziers[0]):',type(beziers[0]))
        print('beziers[0][0]:',beziers[0][0])
        print('type(beziers[0][0]):',type(beziers[0][0]))
        '''self.points.append(self.canvas.create_point(beziers[0][0][0],beziers[0][0][1],3, fill='black', tag='point'))
        self.points.append(self.canvas.create_point(beziers[0][1][0],beziers[0][1][1],3, fill='black', tag='point'))
        self.points.append(self.canvas.create_point(beziers[0][2][0],beziers[0][2][1],3, fill='black', tag='point'))
        self.points.append(self.canvas.create_point(beziers[0][3][0],beziers[0][3][1],3, fill='black', tag='point'))'''
        print('len(beziers):',len(beziers))
        print('len(beziers[0]):',len(beziers[0]))
        for bezier in beziers:
            self.canvas.create_bezier(bezier, tag='bezier')


if __name__ == '__main__':
    o = MainObject()
    o.run()





In [1]:
from numpy import array
points=[(16.000 ,-98.600),
(22.000 ,-97.400),
(30.600 ,-95.100),
(36.500 ,-93.000),
(48.100 ,-87.500),
(53.400 ,-84.400),
(58.700 ,-80.800),
(68.200 ,-73.000),
(72.600 ,-68.700),
(76.400 ,-64.500),
(80.200 ,-59.600),
(83.800 ,-54.400),
(86.800 ,-49.500),
(89.600 ,-44.100),
(92.100 ,-38.400),
(94.200 ,-33.000),
(96.900 ,-24.400),
(99.000 ,-13.900),
(99.800 ,-5.200 ),
(99.700 ,6.200  ),
(98.700 ,15.100 ),
(97.500 ,21.200 ),
(95.300 ,29.700 ),
(93.400 ,35.500 ),
(88.000 ,47.200 ),
(84.800 ,52.700 ),
(81.500 ,57.800 ),
(77.500 ,63.000 ),
(73.600 ,67.500 ),
(69.300 ,71.900 ),
(64.500 ,76.300 ),
(59.800 ,80.000 ),
(51.600 ,85.600 ),
(45.300 ,89.000 ),
(39.600 ,91.600 ),
(33.700 ,94.000 ),
(25.100 ,96.700 ),
(13.900 ,99.000 ),
(5.200 ,99.800  ),
(-7.200 ,99.600 ),
(-16.000,98.600 ),
(-22.000,97.400 ),
(-30.600,95.100 ),
(-36.500,93.000 ),
(-48.100,87.500 ),
(-53.400,84.400 ),
(-58.700,80.800 ),
(-68.200,73.000 ),
(-72.600,68.700 ),
(-76.400,64.500 ),
(-80.200,59.600 ),
(-83.800,54.400 ),
(-86.800,49.500 ),
(-89.600,44.100 ),
(-92.100,38.400 ),
(-94.200,33.000 ),
(-96.900,24.400 ),
(-99.000,13.900 ),
(-99.800,5.200  ),
(-99.600,-7.200 ),
(-98.600,-16.000),
(-97.400,-22.000),
(-95.100,-30.600),
(-93.000,-36.500),
(-87.500,-48.100),
(-84.400,-53.400),
(-80.800,-58.700),
(-73.000,-68.200),
(-68.700,-72.600),
(-64.500,-76.400),
(-59.600,-80.200),
(-54.400,-83.800),
(-49.500,-86.800),
(-44.100,-89.600),
(-38.400,-92.100),
(-33.000,-94.200),
(-24.400,-96.900),
(-13.900,-99.000),
(-5.200 ,-99.800),
(7.200 ,-99.600 ),
]
w=array(points)
for t in w:
    print(str(t[0])+','+str(t[1])+',')

16.0,-98.6,
22.0,-97.4,
30.6,-95.1,
36.5,-93.0,
48.1,-87.5,
53.4,-84.4,
58.7,-80.8,
68.2,-73.0,
72.6,-68.7,
76.4,-64.5,
80.2,-59.6,
83.8,-54.4,
86.8,-49.5,
89.6,-44.1,
92.1,-38.4,
94.2,-33.0,
96.9,-24.4,
99.0,-13.9,
99.8,-5.2,
99.7,6.2,
98.7,15.1,
97.5,21.2,
95.3,29.7,
93.4,35.5,
88.0,47.2,
84.8,52.7,
81.5,57.8,
77.5,63.0,
73.6,67.5,
69.3,71.9,
64.5,76.3,
59.8,80.0,
51.6,85.6,
45.3,89.0,
39.6,91.6,
33.7,94.0,
25.1,96.7,
13.9,99.0,
5.2,99.8,
-7.2,99.6,
-16.0,98.6,
-22.0,97.4,
-30.6,95.1,
-36.5,93.0,
-48.1,87.5,
-53.4,84.4,
-58.7,80.8,
-68.2,73.0,
-72.6,68.7,
-76.4,64.5,
-80.2,59.6,
-83.8,54.4,
-86.8,49.5,
-89.6,44.1,
-92.1,38.4,
-94.2,33.0,
-96.9,24.4,
-99.0,13.9,
-99.8,5.2,
-99.6,-7.2,
-98.6,-16.0,
-97.4,-22.0,
-95.1,-30.6,
-93.0,-36.5,
-87.5,-48.1,
-84.4,-53.4,
-80.8,-58.7,
-73.0,-68.2,
-68.7,-72.6,
-64.5,-76.4,
-59.6,-80.2,
-54.4,-83.8,
-49.5,-86.8,
-44.1,-89.6,
-38.4,-92.1,
-33.0,-94.2,
-24.4,-96.9,
-13.9,-99.0,
-5.2,-99.8,
7.2,-99.6,


In [2]:
from bezier import *
from fitCurves import *
beziers=fitCurve(w,1)
for b in beziers:
    for e in b:
        print(str(e[0])+','+str(e[1])+',')

16.0,-98.6,
31.237767766566883,-95.55244644668664,
46.229762044455036,-90.4054535603522,
58.7,-80.8,
58.7,-80.8,
77.36365439255798,-66.42394188681345,
91.1004615721624,-47.47732999410381,
96.9,-24.4,
96.9,-24.4,
109.22377079263016,24.638337945674223,
81.45849130087805,77.20218581831183,
33.7,94.0,
33.7,94.0,
20.304907895732587,98.71137722288027,
6.95229193477324,100.40107312838339,
-7.2,99.6,
-7.2,99.6,
-71.81518625178327,95.94253662725754,
-119.35681053804832,24.190024265242883,
-93.0,-36.5,
-93.0,-36.5,
-80.10745508539677,-66.18678105336272,
-56.18684838071406,-88.91168208233366,
-24.4,-96.9,
-24.4,-96.9,
-13.594971651881137,-99.61539979429165,
-3.881464750912037,-99.77873330243406,
7.2,-99.6,


In [5]:
changshu=array([[-1,3,-3,1],[3,-6,3,0],[-3,3,0,0],[1,0,0,0]])
print(changshu)
X=array([[16.0],[31.237767766566883],[46.229762044455036],[58.7]])
print(X)

[[-1  3 -3  1]
 [ 3 -6  3  0]
 [-3  3  0  0]
 [ 1  0  0  0]]
[[16.        ]
 [31.23776777]
 [46.22976204]
 [58.7       ]]


In [6]:
xishu=changshu.dot(X)
print(xishu)

[[-2.27598283]
 [-0.73732047]
 [45.7133033 ]
 [16.        ]]


In [7]:
t=0.021883716134577624
T=array([[t**3,t**2,t,1]])
print(T)

[[1.04800467e-05 4.78897032e-04 2.18837161e-02 1.00000000e+00]]


In [9]:
Y=array([[-98.6],[-95.55244644668664],[-90.4054535603522],[-80.8]])
y=T.dot(changshu.dot(Y))
print(y)

[[-98.39688364]]


In [79]:
import sympy
t=sympy.Symbol('t')
q=sympy.solve(-2.27598283*t**3-0.73732047*t**2+45.7133033*t-1,t)
print(type(q[0]))

<class 'sympy.core.add.Add'>


In [76]:
print(q[0])

print(q[0].as_real_imag())

print(q[1].as_real_imag()[0])
print(q[2].as_coeff_Add())
print(q[0])
print(q[1])
print(q[2])
print(type(q[0]))

-4.65704966473876 + 0.e-22*I
(-4.65704966473876, 0.e-22)
0.0218837161345758
(4.31120899239112, -0.e-22*I)
-4.65704966473876 + 0.e-22*I
0.0218837161345758 + 0.e-22*I
4.31120899239112 - 0.e-22*I
<class 'sympy.core.add.Add'>


In [77]:
dir(q)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [67]:
print(q[2].atoms())
print(q[1].as_real_imag())
print(q[1].as_coefficients_dict())

{4.31120899239112, -0.e-22, I}
(0.0218837161345758, 0.e-22)
defaultdict(<class 'int'>, {1: 0.0218837161345758, I: 0.e-22})


In [72]:
l=array([[16.0,-98.6],[31.237767766566883,-95.55244644668664],[46.229762044455036,-90.405453560352],[58.7,-80.8,]])
print(len(l))
print(l.shape)

4
(4, 2)


In [12]:
dir(beziers)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [13]:
xishu=array([[-1,3,-3,1],[3,-6,3,0],[-3,3,0,0]])

In [14]:
print(xishu.shape)

(3, 4)


In [15]:
print(xishu)

[[-1  3 -3  1]
 [ 3 -6  3  0]
 [-3  3  0  0]]


In [16]:
from numpy import linalg

In [17]:
dir(xishu)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [18]:
a=linalg.inv(xishu)
print(a)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
print(linalg.inv(a))

In [ ]:
print(a*xishu)
print(shape(a*xishu))

In [ ]:
print(a.dot(xishu))

In [ ]:
import numpy as np

In [ ]:
t=np.array([[0,0,0,1]])
print(t.shape)

In [ ]:
xishu=np.array([[-1,3,-3,1],[3,-6,3,0],[-3,3,0,0],[1,0,0,0]])

print(xishu)

In [ ]:
w=t.dot(xishu)
print(w)

In [ ]:
pt=np.array([[16.0,-98.6,31.237767766566883,-95.55244644668664],[46.229762044455036,-90.4054535603522,
58.7,-80.8,]])
print(pt.shape)


In [ ]:
pt=np.transpose(pt)
print(pt)

In [ ]:
x=np.linalg.solve(xishu,pt)
print(x)

In [ ]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]]))
print(b)

In [ ]:
x = np.linalg.solve(A,b)
print(x)

In [ ]:
a=np.array([[1,2,3,4]])
print(a)

In [ ]:
b=a.T
print(b)

In [ ]:
print(b.dot(a))

In [ ]:
print(a*b)

In [ ]:
xishu=np.array([[-1,3,-3,1],[3,-6,3,0],[-3,3,0,0],[1,0,0,0]])

print(xishu)

In [ ]:
p03=np.array([[16.0,-98.6],[31.237767766566883,-95.55244644668664],[46.229762044455036,-90.4054535603522],
[58.7,-80.8,]])
print(p03.shape)
print(p03)

In [ ]:
q=xishu.dot(p03)
print(q)

In [ ]:
p45=np.array([[0,0],[60,-100]])
print(p45)

In [ ]:
xishu1=np.array([[-1,1],[1,0]])
print(xishu1)

In [ ]:
x=xishu1.dot(p45)
print(x)

In [ ]:
t1=0.94132
t2=0.84865

In [ ]:
sant=np.array([[t2**3,t2**2,t2,1]])
print(sant)

In [ ]:
print(sant.dot(q))

In [ ]:
yit=np.array([[t1,1]])
print(yit)

In [ ]:
print(yit.dot(x))

In [ ]:
print(xishu[2][1])

In [ ]:
x=np.array([[16.0]])
print(x)

In [ ]:
A=np.array([[16.0],[31.237767766566883],[46.229762044455036],[58.7]])
print(A)
print(A.shape)

In [ ]:
print(A.T)

In [ ]:
mi=A.dot(A.I)
print(mi)
invermi=linalg.inv(mi)
print(invermi)
print(linalg.inv(invermi))

In [ ]:
print(a*k)

In [19]:
import numpy


In [29]:
x=numpy.matrix([[1]])
print(x)
print(x.shape)

[[1]]
(1, 1)


In [27]:
dir(x)

['A',
 'A1',
 'H',
 'I',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__p

In [31]:
A=numpy.matrix([[16],[31.237767766566883],[46.229762044455036],[58.7]])
print(A)

[[16.        ]
 [31.23776777]
 [46.22976204]
 [58.7       ]]


In [36]:
invA=A.I
print(invA)

[[0.00234787 0.00458389 0.00678385 0.00861376]]


In [64]:
x=numpy.matrix([[17]])
print(x)

[[17]]


In [65]:
w=x.dot(invA)
print(w)
print(w.shape)

[[0.03991384 0.0779262  0.11532545 0.1464339 ]]
(1, 4)


In [66]:
yarr=numpy.matrix([[-98.6],[-95.55244644668664],[-90.4054535603522],[-80.8]])
print(yarr)
print(yarr.shape)

[[-98.6       ]
 [-95.55244645]
 [-90.40545356]
 [-80.8       ]]
(4, 1)


In [67]:
y=w.dot(yarr)

In [68]:
print(y)

[[-33.63945248]]


In [73]:
changshu=numpy.matrix([[-1,3,-3,1],[3,-6,3,0],[-3,3,0,0],[1,0,0,0]])
t=w.dot(changshu.I)
print(t)

[[0.1464339  0.18487571 0.24929293 0.37959939]]


In [74]:
t=2.63*t

In [75]:
print(t)

[[0.38512115 0.48622313 0.65564041 0.9983464 ]]


In [76]:
a=numpy.matrix([[1,2,3],[2,5,4],[3,5,1]])
a.I


matrix([[ 1.5, -1.3,  0.7],
        [-1. ,  0.8, -0.2],
        [ 0.5, -0.1, -0.1]])

In [77]:
a.dot(a.I)

matrix([[ 1.00000000e+00, -9.71445147e-17,  2.77555756e-17],
        [ 4.44089210e-16,  1.00000000e+00,  1.66533454e-16],
        [ 1.11022302e-16,  1.52655666e-16,  1.00000000e+00]])

In [82]:
t=1
tt=numpy.matrix([[t**3,t**2,t,1]])

In [83]:
tt.dot(changshu.dot(A))

matrix([[58.7]])

In [84]:
x.dot(A.I.dot(changshu.I))

matrix([[0.1464339 , 0.18487571, 0.24929293, 0.37959939]])

In [85]:
A.dot(A.I)

matrix([[0.03756597, 0.07334231, 0.1085416 , 0.13782014],
        [0.07334231, 0.14319062, 0.21191234, 0.26907459],
        [0.1085416 , 0.21191234, 0.31361578, 0.39821201],
        [0.13782014, 0.26907459, 0.39821201, 0.50562763]])

In [1]:
from numpy import array
bezier_one=array([[0,-100],[60,0]])
bezier_three=array([[16.0,-98.6],[31.237767766566883,-95.55244644668664],[46.229762044455036,-90.4054535603522],[58.7,-80.8,]])
bezier_one_other=array([[0,0],[60,-100]])

0
61


NameError: name 'bezier' is not defined

In [5]:
import bezier
        
print(bezier.getNode(bezier_one,bezier_one_other))
print(bezier.getNode(bezier_one_other,bezier_three))
print(bezier.getNode(bezier_one,bezier_three))

0
61


NameError: name 'bezier' is not defined